-- Seed source registry from planning pack register.
-- Safe to re-run.
INSERT INTO source.sources
    (name, organization, homepage_url, authority_level, geographic_scope, domain, commercial_use_status, license_summary, ai_use_allowed, cache_allowed, export_allowed, raw_data_allowed, metadata)
VALUES
('USGS The National Map', 'USGS', 'https://www.usgs.gov/programs/national-geospatial-program/national-map', 'official_primary', 'US', 'Terrain/elevation/hydro/boundaries', 'unknown', 'Physical screening only; check data vintages', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-001", "source_type": "Public official", "mvp_priority": "Must", "use": "Elevation/slope and base layers", "caveats": "Physical screening only; check data vintages"}'::jsonb),
('FEMA NFHL', 'FEMA', 'https://www.fema.gov/flood-maps/national-flood-hazard-layer', 'official_primary', 'US', 'Flood', 'approved', 'Modernized/effective-map limits; not all flood risk', 'approved', 'approved', 'approved', 'approved', '{"source_registry_id": "DS-002", "source_type": "Public official", "mvp_priority": "Must", "use": "Flood hazard overlay", "caveats": "Modernized/effective-map limits; not all flood risk", "license_status": "approved", "redistribution_status": "approved", "attribution_required_status": "yes", "freshness_class": "reviewed", "last_checked_at": "2026-06-05", "review_owner": "data-governance", "review_status": "approved"}'::jsonb),
('USDA Web Soil Survey/SSURGO', 'USDA NRCS', 'https://websoilsurvey.nrcs.usda.gov/', 'official_primary', 'US', 'Soils', 'unknown', 'Not a substitute for site-specific test', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-003", "source_type": "Public official", "mvp_priority": "Must", "use": "Soil/septic/ag proxy", "caveats": "Not a substitute for site-specific test"}'::jsonb),
('National Wetlands Inventory', 'USFWS', 'https://www.fws.gov/program/national-wetlands-inventory', 'official_primary', 'US', 'Wetlands', 'unknown', 'Not jurisdictional delineation', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-004", "source_type": "Public official", "mvp_priority": "Must", "use": "Wetland/deepwater screening", "caveats": "Not jurisdictional delineation"}'::jsonb),
('USGS Water Data APIs', 'USGS', 'https://api.waterdata.usgs.gov/', 'official_primary', 'US', 'Water monitoring', 'unknown', 'Monitoring proximity may be weak proxy', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-005", "source_type": "Public official", "mvp_priority": "Should", "use": "Streamflow/groundwater/water quality context", "caveats": "Monitoring proximity may be weak proxy"}'::jsonb),
('EPA ECHO', 'EPA', 'https://echo.epa.gov/resources/echo-data/about-the-data', 'official_primary', 'US', 'Environmental compliance', 'unknown', 'Nearby facility does not prove subject contamination', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-006", "source_type": "Public official", "mvp_priority": "Should", "use": "Regulated facilities/violations/enforcement", "caveats": "Nearby facility does not prove subject contamination"}'::jsonb),
('BLM MLRS', 'BLM', 'https://www.blm.gov/services/land-records/mlrs', 'official_primary', 'Federal lands/US', 'Mineral/land records', 'unknown', 'Does not resolve private mineral rights', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-007", "source_type": "Public official", "mvp_priority": "Later", "use": "Mining claims/public land records", "caveats": "Does not resolve private mineral rights"}'::jsonb),
('USGS MRDS', 'USGS', 'https://mrdata.usgs.gov/mrds/', 'official_secondary', 'US/global selected', 'Minerals', 'unknown', 'Systematic updates ceased; treat as historical screening', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-008", "source_type": "Public/stale official", "mvp_priority": "Later", "use": "Mineral occurrence screening", "caveats": "Systematic updates ceased; treat as historical screening"}'::jsonb),
('National Zoning Atlas', 'NZA', 'https://www.zoningatlas.org/', 'official_secondary', 'US partial', 'Zoning', 'unknown', 'Coverage incomplete', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-009", "source_type": "Nonprofit/open where available", "mvp_priority": "Could", "use": "Zoning baseline where available", "caveats": "Coverage incomplete"}'::jsonb),
('County GIS parcels', 'County', 'Varies', 'official_primary', 'County', 'Parcels', 'unknown', 'Approximate; not survey', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-010", "source_type": "Local official/varies", "mvp_priority": "Must", "use": "Parcel geometry and local attributes", "caveats": "Approximate; not survey"}'::jsonb),
('County assessor', 'County', 'Varies', 'official_primary', 'County', 'Assessor/tax', 'unknown', 'Schema/access varies', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-011", "source_type": "Local official", "mvp_priority": "Must", "use": "Assessed value, tax year, situs", "caveats": "Schema/access varies"}'::jsonb),
('County recorder', 'County', 'Varies', 'official_primary', 'County', 'Deeds/easements', 'unknown', 'Often manual/search-limited', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-012", "source_type": "Local official", "mvp_priority": "Should", "use": "Recorded documents, easements, covenants", "caveats": "Often manual/search-limited"}'::jsonb),
('State well logs', 'State agency', 'Varies', 'unknown', 'State', 'Water/wells', 'unknown', 'May not prove viability', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-013", "source_type": "State official", "mvp_priority": "Should", "use": "Nearby well context", "caveats": "May not prove viability"}'::jsonb),
('State water rights', 'State agency', 'Varies', 'unknown', 'State', 'Water rights', 'unknown', 'Complex and jurisdiction-specific', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-014", "source_type": "State official", "mvp_priority": "Later", "use": "Legal water-use screening", "caveats": "Complex and jurisdiction-specific"}'::jsonb),
('State geological survey', 'State agency', 'Varies', 'unknown', 'State', 'Geology/minerals', 'unknown', 'Varies by state', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-015", "source_type": "State official", "mvp_priority": "Later", "use": "Geologic hazards/resources", "caveats": "Varies by state"}'::jsonb),
('OpenStreetMap/Overture', 'OSM/Overture', 'https://www.openstreetmap.org/', 'open_community', 'Global', 'Roads/buildings/base map', 'unknown', 'Not authoritative for legal access', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-016", "source_type": "Open community/open data", "mvp_priority": "Should", "use": "Access/infrastructure proxy", "caveats": "Not authoritative for legal access"}'::jsonb),
('Commercial parcel vendor', 'Vendor', 'TBD', 'commercial_normalized', 'US/Canada or broader', 'Parcels/ownership', 'unknown', 'License/cost blocker', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-017", "source_type": "Commercial", "mvp_priority": "Must", "use": "Normalized parcel/ownership data", "caveats": "License/cost blocker"}'::jsonb),
('Commercial comps/listings vendor', 'Vendor', 'TBD', 'commercial_normalized', 'Varies', 'Market', 'unknown', 'License/cost/export blocker', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-018", "source_type": "Commercial", "mvp_priority": "Should", "use": "Market context", "caveats": "License/cost/export blocker"}'::jsonb),
('Commercial zoning vendor', 'Vendor', 'TBD', 'commercial_normalized', 'Varies', 'Zoning', 'unknown', 'Must verify with official local sources', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-019", "source_type": "Commercial", "mvp_priority": "Could", "use": "Normalized zoning/allowed uses", "caveats": "Must verify with official local sources"}'::jsonb),
('NOAA climate/weather', 'NOAA', 'https://www.noaa.gov/', 'official_primary', 'US', 'Climate/weather', 'unknown', 'Not full forward-looking parcel risk', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-020", "source_type": "Public official", "mvp_priority": "Later", "use": "Climate history/context", "caveats": "Not full forward-looking parcel risk"}'::jsonb),
('FCC Broadband Map', 'FCC', 'https://broadbandmap.fcc.gov/', 'official_primary', 'US', 'Broadband', 'unknown', 'Coverage/provider claims may need verification', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-021", "source_type": "Public official", "mvp_priority": "Could", "use": "Broadband availability proxy", "caveats": "Coverage/provider claims may need verification"}'::jsonb),
('Census TIGER/ACS', 'Census', 'https://www.census.gov/', 'official_primary', 'US', 'Boundaries/demographics', 'unknown', 'Fair housing care', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-022", "source_type": "Public official", "mvp_priority": "Later", "use": "Admin boundaries; avoid protected-class scoring", "caveats": "Fair housing care"}'::jsonb),
('Local zoning ordinance PDFs', 'County/municipality', 'Varies', 'official_primary', 'Local', 'Zoning/legal text', 'unknown', 'Hard to parse; source/date caveats', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-023", "source_type": "Local official", "mvp_priority": "Must", "use": "Allowed use/minimum lot size/overlays", "caveats": "Hard to parse; source/date caveats"}'::jsonb),
('Title company/manual report', 'Title company', 'TBD', 'user_supplied', 'Parcel', 'Title/access/easements', 'unknown', 'External professional source', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-024", "source_type": "Professional/manual", "mvp_priority": "Later", "use": "Verification input", "caveats": "External professional source"}'::jsonb),
('Surveyor/manual report', 'Licensed surveyor', 'TBD', 'user_supplied', 'Parcel', 'Boundary', 'unknown', 'External professional source', 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-025", "source_type": "Professional/manual", "mvp_priority": "Later", "use": "Boundary verification", "caveats": "External professional source"}'::jsonb)
ON CONFLICT (name, organization) DO UPDATE SET
    homepage_url = EXCLUDED.homepage_url,
    authority_level = EXCLUDED.authority_level,
    geographic_scope = EXCLUDED.geographic_scope,
    domain = EXCLUDED.domain,
    license_summary = EXCLUDED.license_summary,
    metadata = source.sources.metadata || EXCLUDED.metadata;
