-- Seed source registry from planning pack register.
-- Safe to re-run.
INSERT INTO source.sources
    (name, organization, homepage_url, authority_level, geographic_scope, domain, commercial_use_status, license_summary, attribution_required, ai_use_allowed, cache_allowed, export_allowed, raw_data_allowed, metadata)
VALUES
('USGS The National Map', 'USGS', 'https://www.usgs.gov/nationalmap', 'official_primary', 'US', 'Terrain/elevation/hydro/boundaries', 'approved-with-restrictions', 'Physical screening only; not survey-grade; check product metadata, scale, accuracy, source date, and third-party notices', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-001", "source_type": "Public official", "mvp_priority": "Must", "use": "Elevation/slope and base layers", "caveats": "Physical screening only; not survey-grade; check product metadata, scale, accuracy, source date, and third-party notices", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-05", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('FEMA NFHL', 'FEMA', 'https://www.fema.gov/flood-maps/national-flood-hazard-layer', 'official_primary', 'US', 'Flood', 'restricted', 'Effective NFHL screening only; not all flood risk; official use requires FEMA standards and proper base-map accuracy; cite FEMA and state non-endorsement', true, 'restricted', 'restricted', 'approved-with-restrictions', 'restricted', '{"source_registry_id": "DS-002", "source_type": "Public official", "mvp_priority": "Must", "use": "Flood hazard overlay", "caveats": "Effective NFHL screening only; not all flood risk; official use requires FEMA standards and proper base-map accuracy; cite FEMA and state non-endorsement", "license_status": "approved-with-restrictions", "redistribution_status": "restricted", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-05", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('USDA Web Soil Survey/SSURGO', 'USDA NRCS', 'https://websoilsurvey.nrcs.usda.gov/', 'official_primary', 'US', 'Soils', 'approved-with-restrictions', 'Screening only; not a substitute for site-specific soil, septic, engineering, or permitting review; cite USDA/NRCS and preserve survey/refresh metadata', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-003", "source_type": "Public official", "mvp_priority": "Must", "use": "Soil/septic/ag proxy", "caveats": "Screening only; not a substitute for site-specific soil, septic, engineering, or permitting review; cite USDA/NRCS and preserve survey/refresh metadata", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-05", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('National Wetlands Inventory', 'USFWS', 'https://www.fws.gov/program/national-wetlands-inventory', 'official_primary', 'US', 'Wetlands', 'approved-with-restrictions', 'Screening only; not jurisdictional delineation, Clean Water Act, permitting, or buildability determination; cite USFWS/NWI and preserve metadata/published-date/project caveats', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-004", "source_type": "Public official", "mvp_priority": "Must", "use": "Wetland/deepwater screening", "caveats": "Screening only; not jurisdictional delineation, Clean Water Act, permitting, or buildability determination; cite USFWS/NWI and preserve metadata/published-date/project caveats", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-05", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('USGS Water Data APIs', 'USGS', 'https://api.waterdata.usgs.gov/', 'official_primary', 'US', 'Water monitoring', 'unknown', 'Monitoring proximity may be weak proxy', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-005", "source_type": "Public official", "mvp_priority": "Should", "use": "Streamflow/groundwater/water quality context", "caveats": "Monitoring proximity may be weak proxy"}'::jsonb),
('EPA ECHO', 'EPA', 'https://echo.epa.gov/resources/echo-data/about-the-data', 'official_primary', 'US', 'Environmental compliance', 'unknown', 'Nearby facility does not prove subject contamination', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-006", "source_type": "Public official", "mvp_priority": "Should", "use": "Regulated facilities/violations/enforcement", "caveats": "Nearby facility does not prove subject contamination"}'::jsonb),
('BLM MLRS', 'BLM', 'https://gis.blm.gov/nlsdb/rest/services/Mining_Claims/MiningClaims/MapServer', 'official_primary', 'Federal lands/US', 'Mineral/land records', 'approved-with-restrictions', 'Active BLM MLRS mining-claim geospatial context only; federal/public-land record scope; PLSS-derived geometries may be approximate, missing, or mapped only to section/county; no private mineral-rights, claim-boundary, title, mine-hazard, resource-value, extraction, environmental-liability, buildability, appraisal, lending, insurance, or investment conclusions', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-007", "source_type": "Public official", "mvp_priority": "Later", "use": "Active federal mining claim context", "caveats": "Active BLM MLRS mining-claim geospatial context only; federal/public-land record scope; PLSS-derived geometries may be approximate, missing, or mapped only to section/county; no private mineral-rights, claim-boundary, title, mine-hazard, resource-value, extraction, environmental-liability, buildability, appraisal, lending, insurance, or investment conclusions", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-11", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('USGS MRDS', 'USGS', 'https://mrdata.usgs.gov/mrds/', 'official_secondary', 'US/global selected', 'Minerals', 'approved-with-restrictions', 'Historical mineral-occurrence screening only; systematic updates ceased in 2011; no mineral-rights, mine-hazard, resource-value, extraction, environmental-liability, investment, or buildability conclusions', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-008", "source_type": "Public/stale official", "mvp_priority": "Later", "use": "Mineral occurrence screening", "caveats": "Historical mineral-occurrence screening only; systematic updates ceased in 2011; no mineral-rights, mine-hazard, resource-value, extraction, environmental-liability, investment, or buildability conclusions", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "historical", "last_checked_at": "2026-06-11", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('National Zoning Atlas', 'NZA', 'https://www.zoningatlas.org/', 'official_secondary', 'US partial', 'Zoning', 'unknown', 'Coverage incomplete', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-009", "source_type": "Nonprofit/open where available", "mvp_priority": "Could", "use": "Zoning baseline where available", "caveats": "Coverage incomplete"}'::jsonb),
('County GIS parcels', 'County', 'Varies', 'official_primary', 'County', 'Parcels', 'approved-with-restrictions', 'Parcel screening only; not a survey, title determination, or buildability finding; cite Chatham County GIS and retrieval date; no owner or value fields exposed', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'restricted', '{"source_registry_id": "DS-010", "source_type": "Local official/varies", "mvp_priority": "Must", "use": "Parcel geometry and local attributes", "caveats": "Parcel screening only; not a survey, title determination, or buildability finding; cite Chatham County GIS and retrieval date; no owner or value fields exposed", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-06", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('County assessor', 'County', 'Varies', 'official_primary', 'County', 'Assessor/tax', 'unknown', 'Schema/access varies', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-011", "source_type": "Local official", "mvp_priority": "Must", "use": "Assessed value, tax year, situs", "caveats": "Schema/access varies"}'::jsonb),
('County recorder', 'County', 'Varies', 'official_primary', 'County', 'Deeds/easements', 'unknown', 'Often manual/search-limited', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-012", "source_type": "Local official", "mvp_priority": "Should", "use": "Recorded documents, easements, covenants", "caveats": "Often manual/search-limited"}'::jsonb),
('State well logs', 'State agency', 'Varies', 'unknown', 'State', 'Water/wells', 'unknown', 'May not prove viability', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-013", "source_type": "State official", "mvp_priority": "Should", "use": "Nearby well context", "caveats": "May not prove viability"}'::jsonb),
('State water rights', 'State agency', 'Varies', 'unknown', 'State', 'Water rights', 'unknown', 'Complex and jurisdiction-specific', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-014", "source_type": "State official", "mvp_priority": "Later", "use": "Legal water-use screening", "caveats": "Complex and jurisdiction-specific"}'::jsonb),
('State geological survey', 'NC Geological Survey', 'https://services2.arcgis.com/kCu40SDxsCGcuUWO/arcgis/rest/services/Geologic_Map_of_North_Carolina/FeatureServer', 'official_primary', 'North Carolina', 'Geology/minerals', 'approved-with-restrictions', 'NCGS 1985 geologic map-unit context only; deprecated statewide 1:500,000 map digitized from 1:250,000 base maps; no hazard, mineral-resource, buildability, appraisal, lending, insurance, or investment conclusions', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-015", "source_type": "State official", "mvp_priority": "Later", "use": "Geologic map-unit context", "caveats": "NCGS 1985 geologic map-unit context only; deprecated statewide 1:500,000 map digitized from 1:250,000 base maps; no hazard, mineral-resource, buildability, appraisal, lending, insurance, or investment conclusions", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "historical", "last_checked_at": "2026-06-11", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('OpenStreetMap/Overture', 'OSM/Overture', 'https://www.openstreetmap.org/', 'open_community', 'Global', 'Roads/buildings/base map', 'unknown', 'Not authoritative for legal access', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-016", "source_type": "Open community/open data", "mvp_priority": "Should", "use": "Access/infrastructure proxy", "caveats": "Not authoritative for legal access"}'::jsonb),
('Commercial parcel vendor', 'Vendor', 'TBD', 'commercial_normalized', 'US/Canada or broader', 'Parcels/ownership', 'unknown', 'License/cost blocker', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-017", "source_type": "Commercial", "mvp_priority": "Must", "use": "Normalized parcel/ownership data", "caveats": "License/cost blocker"}'::jsonb),
('Commercial comps/listings vendor', 'Vendor', 'TBD', 'commercial_normalized', 'Varies', 'Market', 'unknown', 'License/cost/export blocker', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-018", "source_type": "Commercial", "mvp_priority": "Should", "use": "Market context", "caveats": "License/cost/export blocker"}'::jsonb),
('Commercial zoning vendor', 'Vendor', 'TBD', 'commercial_normalized', 'Varies', 'Zoning', 'unknown', 'Must verify with official local sources', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-019", "source_type": "Commercial", "mvp_priority": "Could", "use": "Normalized zoning/allowed uses", "caveats": "Must verify with official local sources"}'::jsonb),
('NOAA climate/weather', 'NOAA', 'https://www.noaa.gov/', 'official_primary', 'US', 'Climate/weather', 'approved-with-restrictions', 'Forecast zone classification only; no historical climate normals or agricultural risk data', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-020", "source_type": "Public official", "mvp_priority": "Later", "use": "NWS forecast zone/administrative climate context", "caveats": "Forecast zone classification only; no historical climate normals or agricultural risk data", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-11", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('FCC Broadband Map', 'FCC', 'https://broadbandmap.fcc.gov/', 'official_primary', 'US', 'Broadband', 'approved', 'ISP self-reported coverage; verify availability directly with providers', false, 'approved', 'approved', 'approved', 'approved', '{"source_registry_id": "DS-021", "source_type": "Public official", "mvp_priority": "Could", "use": "Broadband availability proxy", "caveats": "ISP self-reported coverage; verify availability directly with providers", "review_status": "approved-with-restrictions"}'::jsonb),
('Census TIGER/ACS', 'Census', 'https://www.census.gov/data/developers/data-sets/TIGERweb-map-service.html', 'official_primary', 'US', 'Boundaries/demographics', 'approved-with-restrictions', 'TIGERweb geography context only; ACS demographic variables excluded; non-endorsement notice required; re-identification prohibited', true, 'restricted', 'approved-with-restrictions', 'approved-with-restrictions', 'approved-with-restrictions', '{"source_registry_id": "DS-022", "source_type": "Public official", "mvp_priority": "Later", "use": "Admin boundary context only; ACS demographic variables excluded", "caveats": "TIGERweb tract/block-group geography context only; no ACS demographics, protected-class scoring, neighborhood desirability, market, investment, or residential steering use; cite Census Bureau and non-endorsement notice; no re-identification attempts", "license_status": "approved-with-restrictions", "redistribution_status": "approved-with-restrictions", "attribution_required_status": "yes", "freshness_class": "current-effective", "last_checked_at": "2026-06-11", "review_owner": "operator", "review_status": "approved-with-restrictions"}'::jsonb),
('Local zoning ordinance PDFs', 'County/municipality', 'Varies', 'official_primary', 'Local', 'Zoning/legal text', 'approved-with-restrictions', 'Screening only; recorded-fixture approach; Chatham County NC; verify with Chatham County Planning; full-text redistribution restricted', false, 'approved-with-restrictions', 'restricted', 'restricted', 'restricted', '{"source_registry_id": "DS-023", "source_type": "Local official", "mvp_priority": "Must", "use": "Allowed use/minimum lot size/overlays", "caveats": "Screening only; not a zoning compliance determination; verify with Chatham County Planning; recorded UDO snapshot effective 2025-07-01"}'::jsonb),
('Title company/manual report', 'Title company', 'TBD', 'user_supplied', 'Parcel', 'Title/access/easements', 'unknown', 'External professional source', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-024", "source_type": "Professional/manual", "mvp_priority": "Later", "use": "Verification input", "caveats": "External professional source"}'::jsonb),
('Surveyor/manual report', 'Licensed surveyor', 'TBD', 'user_supplied', 'Parcel', 'Boundary', 'unknown', 'External professional source', false, 'unknown', 'unknown', 'unknown', 'unknown', '{"source_registry_id": "DS-025", "source_type": "Professional/manual", "mvp_priority": "Later", "use": "Boundary verification", "caveats": "External professional source"}'::jsonb)
ON CONFLICT (name, organization) DO UPDATE SET
    homepage_url = EXCLUDED.homepage_url,
    authority_level = EXCLUDED.authority_level,
    geographic_scope = EXCLUDED.geographic_scope,
    domain = EXCLUDED.domain,
    commercial_use_status = EXCLUDED.commercial_use_status,
    license_summary = EXCLUDED.license_summary,
    attribution_required = EXCLUDED.attribution_required,
    ai_use_allowed = EXCLUDED.ai_use_allowed,
    cache_allowed = EXCLUDED.cache_allowed,
    export_allowed = EXCLUDED.export_allowed,
    raw_data_allowed = EXCLUDED.raw_data_allowed,
    metadata = source.sources.metadata || EXCLUDED.metadata;
